# Generated by Django 5.2.13 on 2026-04-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='play', max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('command', models.TextField(blank=True, default='')),
                ('command_description', models.TextField(blank=True, default='')),
                ('expected_output_hint', models.TextField(blank=True, default='')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tutorials.tutorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
